name: Android CI

on:
  push:
    branches:
      - develop  # Change to your branch if needed
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change if needed

      - name: Grant Execute Permissions
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew assembleDebug  # Change to 'assembleRelease' for production builds

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Commit and Push APK to Develop Branch
        run: | 
             git config --global user.name "github-actions[bot]"
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git add app/build/outputs/apk/debug/app-debug.apk
             git commit -m "Add built APK to develop branch"
             git push origin develop
        env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for GitHub Actions to push to your repo